src/NServiceBus.Testing.Tests/InvocationTests.cs
src/NServiceBus.Testing.Tests/SagaTests.cs
src/NServiceBus.Testing.Tests/TestHandlerFixture.cs
src/NServiceBus.Testing/Handler.cs
src/NServiceBus.Testing/Invocations.cs
src/NServiceBus.Testing/Saga.cs

added assertions to test ForwardCurrentMessageTo

---

src/NServiceBus.Testing/ExpectedInvocations/ExpectDelayDeliveryWith.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectDoNotDeliverBefore.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectForwardCurrentMessageTo.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotPublish.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotReply.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSend.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSendLocal.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectPublish.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectReply.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectReplyToOriginator.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSend.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSendLocal.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSendToDestination.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectedMessageInvocation.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectedNotMessageInvocation.cs
src/NServiceBus.Testing/InvokedMessageExtensions.cs
src/NServiceBus.Testing/TestableMessageHandlerContext.cs

introduce typesafe message containers

---

src/NServiceBus.Testing/Handler.cs

For https://github.com/Particular/NServiceBus.Testing/pull/43/files#r54596512

Properly synchronizing handler invocation

---

src/NServiceBus.Testing.Tests/SagaTests.cs
src/NServiceBus.Testing/Invocations.cs
src/NServiceBus.Testing/Saga.cs

fixes #40 by adding a ExpectNotReplyToOriginator method.

Add ExpectNotReplyToOriginator expectation

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing.Tests/Saga/SagaTimeoutTests.cs
src/NServiceBus.Testing.Tests/SagaTests.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectReplyToOriginator.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSendLocal.cs
src/NServiceBus.Testing/Handler.cs
src/NServiceBus.Testing/InvokedMessageExtensions.cs
src/NServiceBus.Testing/Saga.cs
src/NServiceBus.Testing/Test.cs
src/NServiceBus.Testing/TestableMessageHandlerContext.cs

related to https://github.com/Particular/NServiceBus.Testing/issues/12

Adding timeout call to allow user to provide a timespan

---

src/NServiceBus.Testing.Tests/SagaTests.cs
src/NServiceBus.Testing/Saga.cs

@hmemcpy @mat-mcloughlin please review

Fix SetIncomingHeader for Sagas

---

src/NServiceBus.Testing/ExpectedInvocations/ExpectDelayDeliveryWith.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectDoNotContinueDispatching.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectDoNotDeliverBefore.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectForwardCurrentMessageTo.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectHandleCurrentMessageLater.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectInvocation.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDelayDeliveryWith.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDoNotDeliverBefore.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotForwardCurrentMessageTo.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotPublish.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotReply.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSend.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSendLocal.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectPublish.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectReply.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectReplyToOriginator.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSagaData.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSend.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSendLocal.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSendToDestination.cs
src/NServiceBus.Testing/Handler.cs
src/NServiceBus.Testing/NServiceBus.Testing.csproj.DotSettings
src/NServiceBus.Testing/Saga.cs
src/NServiceBus.Testing/TestingContext.cs

Removed ExpectedInvocations namespace

---

src/NServiceBus.Testing.Tests/API/APIApprovals.ApproveTesting.approved.txt
src/NServiceBus.Testing.Tests/API/APIApprovals.cs
src/NServiceBus.Testing.Tests/App_Packages/ApiApprover.3.0.1/PublicApiApprover.cs
src/NServiceBus.Testing.Tests/App_Packages/ApiApprover.3.0.1/PublicApiGenerator.cs
src/NServiceBus.Testing.Tests/ApprovalTestConfig.cs
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing.Tests/packages.config

Connects to #29 and https://github.com/Particular/PlatformDevelopment/issues/709

Approving public API with approval tests

---

LICENSE.md

Adding a license

---

src/NServiceBus.Testing.Tests/API/APIApprovals.ApproveTesting.approved.txt
src/NServiceBus.Testing.Tests/Handler/ExpectNotSendToDestinationTests.cs
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing.Tests/Saga/DiscountPolicySagaTests.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSendToDestination.cs
src/NServiceBus.Testing/Handler.cs
src/NServiceBus.Testing/NServiceBus.Testing.csproj
src/NServiceBus.Testing/Saga.cs

Add ExpectNotSendToDestination ExpectInvocation

---

packaging/nuget/nservicebus.testing.nuspec

Connects to Particular/V6Launch#65

Update NServiceBus dependency version

---

GitVersion.yml
GitVersionConfig.yaml
src/NServiceBus.Testing/NServiceBus.Testing.csproj
src/NServiceBus.Testing/packages.config

Connects to https://github.com/Particular/V6Launch/issues/3
@Particular/nservicebus-maintainers please review and merge

Update GitVersion to 3.6.3

---

src/NServiceBus.Testing.Tests/Handler/ExpectDeferTests.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectDelayDeliveryWith.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectDoNotDeliverBefore.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDelayDeliveryWith.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDoNotDeliverBefore.cs
src/NServiceBus.Testing/NServiceBus.Testing.csproj

fixes #102 
ping @Particular/nservicebus-maintainers 
thoughts about releasing this as 6.0.2 patch release?

Fix ExpectDefer and ExpectNotDefer exception messages

---

src/NServiceBus.Testing/Saga.cs

Saga ExpectNotSend overload incorrectly calling ExpectSend

---

GitVersion.yml
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Prepare beta

---

src/NServiceBus.Testing.Tests/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/Saga/ExpectSagaCompletedTests.cs
src/NServiceBus.Testing.Tests/Saga/SagaTests.cs
src/NServiceBus.Testing/ExpectedInvocations/ExpectSagaCompleted.cs
src/NServiceBus.Testing/Saga.cs
src/NServiceBus.Testing/obsoletes.cs

fixes https://github.com/Particular/NServiceBus.Testing/issues/100

Add ExpectSagaCompleted and ExpectSagaNotCompleted API

---

GitVersion.yml
src/Directory.Build.props
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing.sln
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Here are some minor changes to clean up a few things post-conversion.
It also adds a version range to the NServiceBus dependency.

Project cleanup

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing.sln
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Adds SourceLink support and bumps dependencies.

More cleanup

---

src/NServiceBus.Testing.Tests/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/Saga/SagaTests.cs
src/NServiceBus.Testing/Saga.cs

Accept preconstructed messages

---

src/NServiceBus.Testing.Tests/APIApprovals.cs
src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/ApprovalTestConfig.cs
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing/NServiceBus.Testing.csproj

This updates development tooling on the `master` branch.
Note: This should not be squashed.

master update dev tooling

---

src/NServiceBus.Testing.Tests/APIApprovals.cs
src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/ApprovalTestConfig.cs
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing/NServiceBus.Testing.csproj

This updates development tooling on the `develop` branch.
Note: This should not be squashed.

Update development tooling

---

src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/FakeBuilderTests.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/FakeBuilder.cs

Add generic registration methods to fake builder

---

GitVersion.yml
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Update Particular.Packaging in master

---

GitVersion.yml
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Update Particular.Packaging in release-7.1

---

GitVersion.yml
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Update Particular.Packaging in release-7.2

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

Update test projects to netcoreapp3.1 in release-7.1

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

Update test projects to netcoreapp3.1 in master

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

Update test projects to netcoreapp3.1 in release-7.2

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

Update test projects to NServiceBus 7.2.3 in release-7.2

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

Update test projects to NServiceBus 7.2.3 in release-7.1

---

NOTICE.txt
src/NServiceBus.Testing/DependencyInjection/ServiceCollection.cs

the same way as currently done in Core.

Add apache 2 license for ServiceCollection.cs

---

src/NServiceBus.Testing/DependencyInjection/LightInject.Microsoft.DependencyInjection.g.cs
src/NServiceBus.Testing/DependencyInjection/LightInject.g.cs
src/NServiceBus.Testing/NServiceBus.Testing.csproj

Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482

target framework upgrade

---

src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/Contexts/TestContexts.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/TestableEndpointInstance.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/TestableInvokeHandlerContext.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/TestableMessageProcessingContext.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/TestableMessageSession.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/TestablePipelineContext.cs

Not 100% test coverage, but would have detected the stack overflow before getting to https://github.com/Particular/NServiceBus.Callbacks/pull/229

Fix stack overflow

---

src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

Bump PublicApiGenerator from 10.2.0 to 10.3.0

bump PublicApiGenerator

---

src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Testing.Tests/Sagas/BasicSaga.cs
src/NServiceBus.Testing.Tests/Sagas/DelayedMessages.cs
src/NServiceBus.Testing.Tests/Sagas/ExternalHandlerSimulator.cs
src/NServiceBus.Testing.Tests/Sagas/HeaderMappings.cs
src/NServiceBus.Testing.Tests/Sagas/ReplyMessage.cs
src/NServiceBus.Testing.Tests/Sagas/SendToSelf.cs
src/NServiceBus.Testing.Tests/Sagas/TwoSagas.cs
src/NServiceBus.Testing/NSB.Testing.Fakes/TestingExtensions.cs
src/NServiceBus.Testing/Sagas/QueuedSagaMessage.cs
src/NServiceBus.Testing/Sagas/TestableSaga.cs

relates to https://github.com/Particular/NServiceBus.Testing/pull/340

saga testing tweaks

---

src/NServiceBus.Testing/Sagas/SagaMapper.cs

Saga mapper concurrency improvements

---

src/NServiceBus.Testing.Tests/Sagas/SagaCompletion.cs
src/NServiceBus.Testing/Sagas/TestableSaga.cs

Fix MarkAsComplete on new saga instance

---

src/NServiceBus.Testing.Tests/Sagas/ReplyToOriginator.cs
src/NServiceBus.Testing/Sagas/TestableSaga.cs

Backport of #457 to release-7.4

Populate originator property on saga creation

---

src/NServiceBus.Testing.Tests/Contexts/TestContexts.cs
src/NServiceBus.Testing.Tests/Logging/LoggingForFixtureTests.cs
src/NServiceBus.Testing.Tests/Logging/LoggingTests.cs
src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
src/NServiceBus.Testing.Tests/Sagas/BasicSaga.cs
src/NServiceBus.Testing.Tests/Sagas/DelayedMessages.cs
src/NServiceBus.Testing.Tests/Sagas/ExternalHandlerSimulator.cs
src/NServiceBus.Testing.Tests/Sagas/HeaderMappings.cs
src/NServiceBus.Testing.Tests/Sagas/ReplyMessage.cs
src/NServiceBus.Testing.Tests/Sagas/ReplyToOriginator.cs
src/NServiceBus.Testing.Tests/Sagas/SagaCompletion.cs
src/NServiceBus.Testing.Tests/Sagas/SagaCompletionWithTimeouts.cs
src/NServiceBus.Testing.Tests/Sagas/SendToSelf.cs
src/NServiceBus.Testing.Tests/Sagas/TwoSagas.cs

This PR contains all changes related to assertion model according to the [constraint assertion model](https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html).
Using a script, we apply all [assertion rules](https://docs.nunit.org/articles/nunit-analyzers/NUnit-Analyzers.html#assertion-rules-nunit2001---) provided by the NUnit.Analyzers package. In addition, some manual interventions are done when applicable.

Migrate NUnit assertions to the constraint model in preparation of the NUnit 4 upgrade

---

src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj

This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.PersistenceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.

Upgrading to NUnit4 including all required dependencies
