Particular/NServiceBus.Testing

- src/NServiceBus.Testing.Tests/InvocationTests.cs
- src/NServiceBus.Testing/Invocations.cs
Anybody using NServiceBus.Testing
`ExpectSend` only executes until the first check passes for the specified
type.
The Validate method currently exits on the first instance of check that returns `true`. This makes it impossible for users to test that a particular message is sent multiple times in response to a single
handle.
Issue initially reported by Dave Kennedy
https://github.com/Particular/NServiceBus.Testing/issues/30
connects to #30
> Change Validate to run all checks for type

- src/NServiceBus.Testing.Tests/TestHandlerFixture.cs
- src/NServiceBus.Testing/Handler.cs
It's currently not possible to call `SendToSite` in v5 using the testing framework since the extension methods from the Gateway package cast the `IBus` instance to an `UnicastBus` which fails with the fake bus from the testing framework. Therefore the expectations also don't work any more.
@Particular/nservicebus-maintainers please review
> remove SentToSites expectations

- src/NServiceBus.Testing.Tests/SagaTests.cs
- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/Test.cs
`Test.Saga(..)` now allows you to provide a saga instance which doesn't have an empty constructor.
> Remove empty constructor requirement for Sagas

- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/Test.cs
Remove the `new()` constraint for testable sagas in cases the user already provides an instance of the saga.
> Remove empty ctor requirement for sagas

- src/NServiceBus.Testing.Tests/HandlerTests.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotPublish.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotReply.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSend.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectPublish.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectReply.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectSend.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectedMessageInvocation.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectedNotMessageInvocation.cs
- src/NServiceBus.Testing/Handler.cs
- src/NServiceBus.Testing/InvokedMessageExtensions.cs
- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/TestableMessageHandlerContext.cs
Adds overloads to `ExpectSend` `ExpectPublish` and `ExpectReply` (incl. ExpectNot options) which provide the specific send/publish/reply option so users can verify the options themselves.
This is e.g. required for users to be able to verify options provided by downstream repos like Gateway or Callbacks.
e.g. something like  `ExpectSend<MyMessage>((message, options) => options.GetSite() == "expected site")`
> Add overloads providing access to the send options

- src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
- src/NServiceBus.Testing.Tests/Saga/SagaDataTests.cs
- src/NServiceBus.Testing.Tests/Saga/SagaTimeoutTests.cs
- src/NServiceBus.Testing.sln.DotSettings
- src/NServiceBus.Testing/ExpectedInvocations/ExpectSagaData.cs
- src/NServiceBus.Testing/NServiceBus.Testing.csproj
- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/Test.cs
Allows the user to start a testing session providing a seed `IContainsSagaData`. For example:
```
Test.Saga<TestSaga>(new SagaData { Property = "property" })
```
It also includes the ability to "Expect" certain saga data 
```
Test.Saga<TestSaga>(new SagaData  { Property = "property" })
.ExpectSagaData<SagaData >(data => data.Property == "property")
```
So the user can check their data is in a validate state after calling a handle method.
> Adding the ability to seed saga data

- src/NServiceBus.Testing/Test.cs
re-add `Test.Initialize` to add a proper obsolete message that tells users it's safe to just remove it. I think this is better than just removing it entirely.
@mat-mcloughlin @hmemcpy please review
> Obsolete Test.Initialize

- src/NServiceBus.Testing.Tests/HandlerTests.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectDelayDeliveryWith.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectDoNotDeliverBefore.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectForwardCurrentMessageTo.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDelayDeliveryWith.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDoNotDeliverBefore.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotForwardCurrentMessageTo.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotPublish.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotReply.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSend.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotSendLocal.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectPublish.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectReply.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectSend.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectSendLocal.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectSendToDestination.cs
- src/NServiceBus.Testing/Handler.cs
- src/NServiceBus.Testing/Saga.cs
* Makes most `check` parameters for `ExpectXYZ` expectations optional, defaulting them to `x => true`.
* Also adds ExpectNotReply for sagas.
related to #7 
related to #5
@Particular/nservicebus-maintainers @mat-mcloughlin @hmemcpy please review
> Default expectations

- src/NServiceBus.Testing.Tests/SagaTests.cs
- src/NServiceBus.Testing/Saga.cs
Connects to #29 
Adds overloads to `When` (used in Saga tests for handler invocation). Instead of writing
```.When((s, c) => s.Handle(new SubmitOrder
{
Total = total,
IsRemoteOrder = true
}, c))````
you can now write
```.When<SubmitOrder>(s => s.Handle, m => m.Total = total);````
or 
```.When(s => s.Handle, new SubmitOrder{ Total = total })```
Note that `When` didn't support interface-only messages yet and used `.WhenHandling<IMessage>(m => [...])` instead.
@Particular/nservicebus-maintainers @hmemcpy @mat-mcloughlin please review
> When overloads for handler selection

- src/NServiceBus.Testing.Tests/HandlerTests.cs
- src/NServiceBus.Testing/InvokedMessageExtensions.cs
- src/NServiceBus.Testing/TestableMessageHandlerContext.cs
Make sure operations like `Send` `Publish` and so on are threadsafe. Since the TestableHandlerContext class isn't public (yet) we can't directly test the class, so the tests are currently placed on the handler tests.
> Make TestableHandlerContext operations threadsafe

- src/NServiceBus.Testing.Tests/API/APIApprovals.ApproveTesting.approved.txt
- src/NServiceBus.Testing.Tests/Handler/ExpectSendToDestinationTests.cs
- src/NServiceBus.Testing.Tests/NServiceBus.Testing.Tests.csproj
- src/NServiceBus.Testing/ExpectedInvocations/ExpectSendToDestination.cs
- src/NServiceBus.Testing/Handler.cs
* Improved messages for obsoleted methods
* Removed obsolete attribute from `ExpectSendToDestination` again. This was still supported on the saga and the expectation already implemented. Not sure why this was obsoleted on the handler. Maybe @hmemcpy remembers? (+added a test for it)
@Particular/nservicebus-maintainers @mat-mcloughlin @WojcikMike please have a look
> Improve obsolete messages and implement ExpectSendToDestination

- src/NServiceBus.Testing.Tests/API/APIApprovals.ApproveTesting.approved.txt
- src/NServiceBus.Testing.Tests/Handler/HandlerTests.cs
- src/NServiceBus.Testing.Tests/Saga/SagaTests.cs
- src/NServiceBus.Testing/Handler.cs
- src/NServiceBus.Testing/Saga.cs
Allows Handler and Saga tests to configure the MessageHandlerContext which will be received by the handle method by using `ConfigureHandlerContext` before calling `OnMessage` or `When`.
This is required in case users want to setup properties on the context which can't be set by a provided extension method or parameter.
@Particular/nservicebus-maintainers @WojcikMike @mat-mcloughlin please review
> Allow configuring the context

- src/NServiceBus.Testing.Tests/Timeouts.cs
- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/TimeoutManager.cs
* Users trying to use `WhenSagaTimesOut` without previous call to `When` or `WhenHandle`
```
Test.Saga<TimeoutSaga>()
.ExpectTimeoutToBeSetIn<MyTimeout>((state, expiresIn) => expiresIn == TimeSpan.FromDays(1))
.WhenSagaTimesOut()
```
will throw a `KeyNotFoundException` coming from the `TimeoutManager`. The problem is that this exception doesn't guide the user in any way to do the right thing.
> Better guidance when WhenSagaTimesOut is used without previous RequestTimeout

- src/NServiceBus.Testing.Tests/Handler/HandlerTests.cs
- src/NServiceBus.Testing.Tests/Saga/SagaTests.cs
- src/NServiceBus.Testing/Handler.cs
- src/NServiceBus.Testing/NServiceBus.Testing.csproj
- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/TypeExtensions.cs
- src/NServiceBus.Testing/packages.config
fixes #95 
the testing framework isn't able to handle message hierarchies properly and also invokes only one handle method per message.
@Particular/nservicebus-maintainers please review
> Handle inherited messages correctly

- src/NServiceBus.Testing.Tests/APIApprovals.Approve.approved.txt
- src/NServiceBus.Testing.Tests/Handler/ExpectDeferTests.cs
- src/NServiceBus.Testing.Tests/Saga/ExpectTimeoutTests.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectDoNotDeliverBefore.cs
- src/NServiceBus.Testing/ExpectedInvocations/ExpectNotDoNotDeliverBefore.cs
- src/NServiceBus.Testing/Handler.cs
- src/NServiceBus.Testing/Saga.cs
This PR is intended as a way to demonstrate/discuss what I think is a minor bug in the "old" testing framework. Assertions on non-UTC date times don't work
Change Timeout expectations from DateTime to DateTimeOffset in order to allow assertions on non-UTC time zones.
> Support non-UTC time zones in Timeout assertions

- src/NServiceBus.Testing/NSB.Testing.Fakes/FakeBuilder.cs
To save some significant amount of reflection when registering funcs when you dont have the generic T. 
In my case i want to register mutiple message validators that have been loaded using reflection
> add non generic registers to FakeBuilder

- src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Testing/Handler.cs
- src/NServiceBus.Testing/Saga.cs
- src/NServiceBus.Testing/TypeExtensions.cs
Customers might have tons of those tests but if they are using xunit the GetAwaiter().GetResult() calls will deadlock in certain scenarios. This introduces async variants to allow customers to move to them. This makes it possible to get the tests unstuck from deadlocking and gives them the possibility to gradually then move when the time comes to the new testable overloads
See https://github.com/Particular/NServiceBus.Testing/issues/135#issuecomment-528799797
I'm aware that this contradicts the current async method naming guideline but I think for the testing lib for this specific case this is fine
> Async overloads for OnMessage and When

- src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Testing.Tests/Logging/LoggingForFixtureTests.cs
- src/NServiceBus.Testing.Tests/Logging/LoggingTests.cs
- src/NServiceBus.Testing.sln.DotSettings
- src/NServiceBus.Testing/NSB.Testing.Fakes/AsyncLocal.cs
- src/NServiceBus.Testing/NSB.Testing.Fakes/DefaultTestingLoggerFactory.cs
- src/NServiceBus.Testing/NSB.Testing.Fakes/NamedLogger.cs
- src/NServiceBus.Testing/NSB.Testing.Fakes/TestingLoggerFactory.cs
The testing logging factory is kind of broken. When you write a test like
```
[Test]
public async Task ShouldLogCorrectly()
{
var logStatements = new StringBuilder();
LogManager.Use<TestingLoggerFactory>()
.WriteTo(new StringWriter(logStatements));
var handler = new MyHandlerWithLogging();
await handler.Handle(new MyRequest(), new TestableMessageHandlerContext())
.ConfigureAwait(false);
StringAssert.Contains("Some log message", logStatements.ToString());
}
```
and then write another test like
```
[Test]
public async Task ShouldLogCorrectlyASecondTime()
{
var logStatements = new StringBuilder();
LogManager.Use<TestingLoggerFactory>()
.WriteTo(new StringWriter(logStatements));
var handler = new MyHandlerWithLogging();
await handler.Handle(new MyRequest(), new …
```
> Ability to scope the TestingLoggerFactory

- src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Testing/NSB.Testing.Fakes/TestableMessageSession.cs
`TimeoutMessages` is still non-virtual, because it is non-virtual on `TestablePipelineContext`.
> restore virtual methods on IMessageSession

- .github/workflows/release.yml
This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.
> Use Key Vault certificate for signing - release-7.2

- src/NServiceBus.Testing.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Testing/obsoletes.cs
This API was removed in v8 without being obsoleted: `TestableMessageSession.Extensions`
> Obsolete missing API

- src/NServiceBus.Testing.Tests/Sagas/DelayedMessages.cs
- src/NServiceBus.Testing/Sagas/TestableSaga.cs
Fixes https://github.com/Particular/NServiceBus.Testing/issues/370
Calling `AdvanceTime` could result in an exception:
```
System.InvalidOperationException
Failed to compare two elements in the array.
at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
at System.Linq.OrderedEnumerable`1.ToArray()
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at NServiceBus.Testing.TestableSaga`2.AdvanceTime(TimeSpan timeToAdvance, Func`2 provideContext) in 
```
It seems this has been caused …
> Order by DateTime in TestableSaga.AdavanceTime 

- src/NServiceBus.Testing.Tests/Sagas/ReplyToOriginator.cs
- src/NServiceBus.Testing/Sagas/TestableSaga.cs
Fixes https://github.com/Particular/NServiceBus.Testing/issues/456 by ensuring that the Saga.Originator property is always assigned.
Note that this slightly deviates from NServiceBus.Core which doesn't populate the property when there is no `ReplyTo` header on the message starting a saga. Given this header is almost always sent when sending messages with NServiceBus, and the testable handler context has a default value for the `context.ReplyTo` property, using a default value seems valid. Not setting the value when the header is missing might also be a valid alternative to have a more accurate simulation though.
> Populate originator property on saga creation

- src/NServiceBus.Testing.Tests/Sagas/SagaCompletionWithTimeouts.cs
- src/NServiceBus.Testing/Sagas/TestableSaga.cs
With this change, if two (or more) timeouts will mark the saga as complete and will fire at the same time, the first will mark the saga as complete and create a processing result, while the other timeouts (occuring "after" saga completion) will be consumed, just like in NServiceBus.
> Swallow timeouts occurring after saga completion

- src/NServiceBus.Testing/Sagas/NonDurableStorage/NonDurableSagaPersister.cs
- src/NServiceBus.Testing/Sagas/TestableSaga.cs
This change satisfies the new `IDE0028` analyzer rules in the .NET 8 SDK.
> Use C# 12 collection expressions
